### ISSUE TITLE
关于图片自适应

### ISSUE THREAD

**Issue by hike2008** [Ariel2013/generate_video_from_picture#1]
请问下， 图片自适应应该怎么处理呢，指定了视频分辨率后，不匹配的图片变形比较严重

**Comment by Ariel2013** [comment]
目前我的方案是计算宽高然后按比例缩放，保证不变形，其他的地方用黑色背景。

**Comment by hike2008** [comment]
大致明白，但是我看源码中有这样的判断：
boolean vertical = getImgWidth(files.get(i)) == 3016;
是否不太精确，精确的是否应该是判断图片的宽高比呢；

**Comment by Ariel2013** [comment]
是的，这个仓库的代码还是我之前写demo的时候写的，目标是通过试验api实现效果。

项目里的代码是需要先过滤掉宽高比，大小等不符合要求的图片，然后再根据结果图片的宽高比计算出黑边的大小和位置。

**Comment by hike2008** [comment]
那如果需要适配各种尺寸的图片，那就需要按照图片宽高和生成的视频宽高，按比例缩放宽高对吧，
比如输出540*960的视频，提供了有 720 * 1280 和 1280 * 720的图，那么前者就需要宽高按比例缩小，后者需要宽度按比例缩小后，计算下合适的高度，这样吧

**Comment by Ariel2013** [comment]
是的，计算之后再填充其余的位置。

目前我们产品期望是高斯模糊填充，我暂时实现的是单色填充。

**Comment by hike2008** [comment]
单色填充， pad = 405：320：0：46：black 是使用这样的命令吧？

**Comment by Ariel2013** [comment]
是的

**Comment by hike2008** [comment]
好的，多谢，我试试看

**Comment by Ariel2013** [comment]
不客气 ;-)

**Comment by hike2008** [comment]
试了下，感觉能处理到不变形，但是图片大小还是不能很好的控制，是需要使用scale命令配合一下么？

ffmpeg -threads 8 -y -r 25 -i /Users/lishengqiang/Documents/temp/5.jpg -vf zoompan=z=1.1:x='if(eq(x,0),100,x-1)':s='540*960',pad='540:960:330:0:black' -t 2.0 /Users/lishengqiang/Documents/temp/output/1.mp4
2018-04-24 45:15 INFO  FfmpegUtil >>> 540 --- 540 
 1024 --- 1024

另外scale命令怎么能不改变输出视频尺寸，而改变图片尺寸呢

**Comment by hike2008** [comment]
我尝试了一种做法，把所有图片都转换到指定格式，然后在生成视频，效果应该能达到，但是流程有些繁琐，请教下下面的命令是否有可优化的办法（图片生成新图片）；
ffmpeg -i /Users/lishengqiang/Documents/temp/6.png -vf scale=540:540,pad=540:960:0:210:black /Users/lishengqiang/Documents/temp/6_pad.png
