### ISSUE TITLE
平移动画的平滑度问题

### ISSUE THREAD

**Issue by hike2008** [Ariel2013/generate_video_from_picture#2]
平移动画图片较小时会出现这样的情况，请问该如何优化呢

[有问题的动画视频](https://pan.baidu.com/s/18mo7rqvk7auBDTpowFWxfA)

**Comment by Ariel2013** [comment]
是使用我的demo 的代码吗？之前我试过的平移的动画，没这个问题。能贴一下你的代码么？

**Comment by hike2008** [comment]
是Demo的代码，只是修改了宽高：
private static final int WIDTH = 540;
private static final int HEIGHT = 960;
	
用的下面的图片：
![11](https://user-images.githubusercontent.com/8948629/39234186-220a9296-48a5-11e8-9864-aa736fd3a78a.jpg)
![9](https://user-images.githubusercontent.com/8948629/39234187-22674784-48a5-11e8-855c-c1827854bb5f.jpg)
![10](https://user-images.githubusercontent.com/8948629/39234189-22af0290-48a5-11e8-80c5-a2b37c6b74d5.jpg)
![8](https://user-images.githubusercontent.com/8948629/39234191-22f79898-48a5-11e8-9a45-479a9e6dcaa4.jpg)
![3](https://user-images.githubusercontent.com/8948629/39234193-2340add0-48a5-11e8-8a97-a6e40c5e3a94.jpg)
![1](https://user-images.githubusercontent.com/8948629/39234194-2389f684-48a5-11e8-80f8-41f18fb706df.jpg)

**Comment by hike2008** [comment]
另外视频可能被百度云转码后变了，实际没有抖动那么多遍，可能是2-3次这样

**Comment by Ariel2013** [comment]
这个遇到过，最近也正准备修复这个问题。

应该是因为平移动画我demo写的每帧移动的距离是固定的，而真实情况下我们提供的图片的宽高是不固定的，导致平移到宽高的临界值又重新从头开始了。

准备按图片的宽高自定义平移的速度。最近一直在忙项目的代码，demo的代码得过一阵项目稳定了才能同步。

你可以先试一下，希望对你有帮助。

**Comment by hike2008** [comment]
恩，好的，我初步考虑可能根据图片宽高进行一定的计算去算出位移距离；
谢谢~
